# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubara" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "b758713edec216ac8b003e33bade5ea3e75792c749f859194824bacdcce63d49"
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30d090fda4d5aecc689e3e8e739b01650fd1677d270547dcefb493c556809916"
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b372e0712335cd20f3b12cb78e64e18d1e2024985460c5e2d295b4246c12b7f2"
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67756f50a9c8c032e12b84d3fc87c8efb1f94612b37b1de01bdd8aac72aa0672"
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubara"
  desc "Kubara is a single binary CLI tool written in Go providing a lightweight framework for bootstrapping Kubernetes platforms with production-proven best practices"
  homepage "https://github.com/kubara-io/kubara"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubara"

  # No zap stanza required

end
