# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubara" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_darwin_amd64.tar.gz"
      sha256 "fd914fa26910b615ceb529babfb9b83d4766809f579afab9f2e6dc4c5e4dc3a7"
    end
    on_arm do
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_darwin_arm64.tar.gz"
      sha256 "6589715a551a09b3e5429a7d2b8469340311bd2f3311e3a50c8269832ab8a294"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_linux_amd64.tar.gz"
      sha256 "285ab3eb65c21937e3ade3b008370b03f3368740d1a6cdba2e043d47bcc4804c"
    end
    on_arm do
      url "https://github.com/kubara-io/kubara/releases/download/v#{version}/kubara_#{version}_linux_arm64.tar.gz"
      sha256 "ef696e7752dcf837b27ac7beafd77d12a58228cd07d81efa1344d70e22c73af1"
    end
  end

  name "kubara"
  desc "Kubara is a single binary CLI tool written in Go providing a lightweight framework for bootstrapping Kubernetes platforms with production-proven best practices"
  homepage "https://github.com/kubara-io/kubara"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubara"

  # No zap stanza required

end
